// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Request = 1,
  HttpPart = 2,
  Method = 3,
  Path = 4,
  Version = 5,
  Headers = 6,
  Header = 7,
  HeaderKey = 8,
  HeaderValue = 9,
  Body = 10
