// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zOQOPOOOOOO'#C^'#C^OVOPOOO[OQOOOOOO'#C_'#C_OaOPOOOfOPOOOOOO'#C`'#C`OkOPOOOpOSOOOOOO'#Cc'#CcOxOPO'#CbO}OPO'#CfO!SOSO'#CaO![OPOOO!aOSO,58|OOOO,59Q,59QOOOO-E6d-E6dO!fOWOOOOOO'#Cd'#CdOOOO1G.h1G.hOOOO'#Ch'#ChO!qOWO'#CgO!yOPO'#CeO!yOPO'#CeQOOOOOOOOO-E6f-E6fOOOO,59R,59ROOOO-E6e-E6eO#ROPO,59P",
  stateData: "#Z~O_PO~O`RO~OaSO~O`UO~ObVO~OcXO~OdYOcTP~Oe_O~Oc`O~OdYOcTX~OcbO~OdcO~OceOfhO]XP~OceOfkO~OceO]XX~OceO]Xa~O",
  goto: "!c]PP^adgjnrux!O!YRQORTRRWUR^XT[X]TZX]Rd_RibQ]XRa]QgbSlgmRmhWfbghmRjf",
  nodeNames: "⚠ Request Method Path Version Headers Header HeaderKey HeaderValue Body",
  maxTerm: 22,
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "8[~R`OY!TYZ$uZp!Tpq$zq![!T![!]%g!]!f!T!f!g&e!g!i!T!i!j+e!j!k-V!k!r!T!r!s3s!s;'S!T;'S;=`$o<%lO!T^!^WdSfWaQOY!TZp!Tpq!vq![!T![!]$O!];'S!T;'S;=`$o<%lO!T[!}UdSfWOY!vZ![!v![!]#a!];'S!v;'S;=`#x<%lO!vW#fSfWOY#aZ;'S#a;'S;=`#r<%lO#aW#uP;=`<%l#a[#{P;=`<%l!vY$VUfWaQOY$OZp$Opq#aq;'S$O;'S;=`$i<%lO$OY$lP;=`<%l$O^$rP;=`<%l!T~$zOc~]%TU`PdSfWOY!vZ![!v![!]#a!];'S!v;'S;=`#x<%lO!vZ%nUfWaQOY$OZp$Opq&Qq;'S$O;'S;=`$i<%lO$OX&XSePfWOY#aZ;'S#a;'S;=`#r<%lO#a_&nYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!g!T!g!h'^!h;'S!T;'S;=`$o<%lO!T_'gYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!n!T!n!o(V!o;'S!T;'S;=`$o<%lO!T_(`YdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!g!T!g!h)O!h;'S!T;'S;=`$o<%lO!T_)XYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!v!T!v!w)w!w;'S!T;'S;=`$o<%lO!T_*QYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!g!T!g!h*p!h;'S!T;'S;=`$o<%lO!T_*{WdSfW_PaQOY!TZp!Tpq!vq![!T![!]$O!];'S!T;'S;=`$o<%lO!T_+nYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!g!T!g!h,^!h;'S!T;'S;=`$o<%lO!T_,gYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!v!T!v!w*p!w;'S!T;'S;=`$o<%lO!T_-`YdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!v!T!v!w.O!w;'S!T;'S;=`$o<%lO!T_.XYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!v!T!v!w.w!w;'S!T;'S;=`$o<%lO!T_/QYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!r!T!r!s/p!s;'S!T;'S;=`$o<%lO!T_/yYdSfWaQOY!TZp!Tpq!vq!P!T!P!Q0i!Q![!T![!]$O!];'S!T;'S;=`$o<%lO!T_0rXdSfWaQOY!TZp!Tpq!vq!Q!T!Q![1_![!]$O!];'S!T;'S;=`$o<%lO!T_1jYdSfWaQbPOY!TZp!Tpq!vq!O!T!O!P2Y!P![!T![!]$O!];'S!T;'S;=`$o<%lO!T_2cXdSfWaQOY!TZp!Tpq!vq!Q!T!Q![3O![!]$O!];'S!T;'S;=`$o<%lO!T_3ZWdSfWaQbPOY!TZp!Tpq!vq![!T![!]$O!];'S!T;'S;=`$o<%lO!T_3|^dSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!c!T!c!d4x!d!q!T!q!r7c!r!w!T!w!x,^!x;'S!T;'S;=`$o<%lO!T_5RYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!v!T!v!w5q!w;'S!T;'S;=`$o<%lO!T_5zYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!e!T!e!f6j!f;'S!T;'S;=`$o<%lO!T_6sYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!j!T!j!k*p!k;'S!T;'S;=`$o<%lO!T_7lYdSfWaQOY!TZp!Tpq!vq![!T![!]$O!]!u!T!u!v,^!v;'S!T;'S;=`$o<%lO!T",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Request":[0,1]},
  tokenPrec: 0
})
