// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {httpHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%QOQOPOOOOOO'#C_'#C_OVOPO'#C^O[OPOOOaOQO,58xOfOSOOOOOO'#C`'#C`OqOPO1G.dOOOO'#Ci'#CiOvOSO'#ChO!OOPO'#CfO!OOPO'#CfQOOOOOO!WOPO7+$OOOOO-E6g-E6gOOOO,59S,59SOOOO-E6f-E6fO!]OPO,59QOOOO'#Ca'#CaO!eOPO<<GjO!jOWOAN=UOOOO'#Cd'#CdO!rOPO'#CcO!wOPO'#CgO!|OWO'#CbOOOOG22pG22pO#UOWO,58}OOOO,59R,59ROOOO-E6e-E6eOOOO'#Ce'#CeOOOO1G.i1G.i",
  stateData: "#Z~O`PO~OaSO~OgTO~ObUO~OdWOhZO^YP~Oa]O~OdWOh_O~OdWO^YX~OcbO~OdWO^Ya~OddO~OeeOgUP~OfjO~OdkO~OeeOgUX~OemO~O",
  goto: "!g^PP_behknrvy|!S!^RRORQORVSRc]RidTgdhTfdhRnjR[TQhdRlhQYTS`YaRaZWXTYZaR^X",
  nodeNames: "⚠ Request HttpPart Method Path Version Headers Header HeaderKey HeaderValue Body",
  maxTerm: 24,
  propSources: [httpHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ":e~RbOY!ZYZ${Zp!Zpq%Qq}!Z}!O%m!O![!Z![!]'p!]!f!Z!f!g(n!g!i!Z!i!j-n!j!k/`!k!r!Z!r!s5|!s;'S!Z;'S;=`$u<%lO!Z^!dWeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!];'S!Z;'S;=`$u<%lO!Z[#TUeWhSOY!|Z![!|![!]#g!];'S!|;'S;=`$O<%lO!|S#lShSOY#gZ;'S#g;'S;=`#x<%lO#gS#{P;=`<%l#g[$RP;=`<%l!|U$]UhSbQOY$UZp$Upq#gq;'S$U;'S;=`$o<%lO$UU$rP;=`<%l$U^$xP;=`<%l!Z~%QOd~]%ZUaPeWhSOY!|Z![!|![!]#g!];'S!|;'S;=`$O<%lO!|_%tWhSbQOY$UZp$Upq#gq}$U}!O&^!O;'S$U;'S;=`$o<%lO$U_&eWhSbQOY$UZp$Upq#gq}$U}!O&}!O;'S$U;'S;=`$o<%lO$U_'WWhSbQgXOY$UZp$Upq#gq}$U}!O&}!O;'S$U;'S;=`$o<%lO$UV'wUhSbQOY$UZp$Upq(Zq;'S$U;'S;=`$o<%lO$UT(bSfPhSOY#gZ;'S#g;'S;=`#x<%lO#g_(wYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!g!Z!g!h)g!h;'S!Z;'S;=`$u<%lO!Z_)pYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!n!Z!n!o*`!o;'S!Z;'S;=`$u<%lO!Z_*iYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!g!Z!g!h+X!h;'S!Z;'S;=`$u<%lO!Z_+bYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!v!Z!v!w,Q!w;'S!Z;'S;=`$u<%lO!Z_,ZYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!g!Z!g!h,y!h;'S!Z;'S;=`$u<%lO!Z_-UWeWhS`PbQOY!ZZp!Zpq!|q![!Z![!]$U!];'S!Z;'S;=`$u<%lO!Z_-wYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!g!Z!g!h.g!h;'S!Z;'S;=`$u<%lO!Z_.pYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!v!Z!v!w,y!w;'S!Z;'S;=`$u<%lO!Z_/iYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!v!Z!v!w0X!w;'S!Z;'S;=`$u<%lO!Z_0bYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!v!Z!v!w1Q!w;'S!Z;'S;=`$u<%lO!Z_1ZYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!r!Z!r!s1y!s;'S!Z;'S;=`$u<%lO!Z_2SYeWhSbQOY!ZZp!Zpq!|q!P!Z!P!Q2r!Q![!Z![!]$U!];'S!Z;'S;=`$u<%lO!Z_2{XeWhSbQOY!ZZp!Zpq!|q!Q!Z!Q![3h![!]$U!];'S!Z;'S;=`$u<%lO!Z_3sYeWhSbQcPOY!ZZp!Zpq!|q!O!Z!O!P4c!P![!Z![!]$U!];'S!Z;'S;=`$u<%lO!Z_4lXeWhSbQOY!ZZp!Zpq!|q!Q!Z!Q![5X![!]$U!];'S!Z;'S;=`$u<%lO!Z_5dWeWhSbQcPOY!ZZp!Zpq!|q![!Z![!]$U!];'S!Z;'S;=`$u<%lO!Z_6V^eWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!c!Z!c!d7R!d!q!Z!q!r9l!r!w!Z!w!x.g!x;'S!Z;'S;=`$u<%lO!Z_7[YeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!v!Z!v!w7z!w;'S!Z;'S;=`$u<%lO!Z_8TYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!e!Z!e!f8s!f;'S!Z;'S;=`$u<%lO!Z_8|YeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!j!Z!j!k,y!k;'S!Z;'S;=`$u<%lO!Z_9uYeWhSbQOY!ZZp!Zpq!|q![!Z![!]$U!]!u!Z!u!v.g!v;'S!Z;'S;=`$u<%lO!Z",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Request":[0,1]},
  tokenPrec: 0
})
