// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Request = 1,
  Method = 2,
  Path = 3,
  Version = 4,
  Headers = 5,
  Header = 6,
  HeaderKey = 7,
  HeaderValue = 8,
  Body = 9
