#!/bin/bash
set -euxo pipefail

run/.impl/clean-local

if [[ "$1" = "offline" ]]
then
    echo "Running in ofline mode"
else
    rm -rf */node_modules/
    rm -rf node_modules/
fi

rm -rf */build/
rm -rf build/
rm -rf */dist/
