#!/bin/bash
set -euxo pipefail

semver="1.0.0"

# downlink tests
run/.impl/relink_dependency test_integration "@ruzito/oas-ls-backend" "$semver"

# downlink benchmarks
run/.impl/relink_dependency test_benchmarks "@ruzito/oas-ls-backend" "$semver"

# downlink codemirror frontens
run/.impl/relink_dependency frontend_codemirror "@ruzito/oas-ls-backend" "$semver"

# downlink end_to_end
# run/.impl/relink_dependency test_codemirror "@ruzito/oas-ls-backend" "$semver"
run/.impl/relink_dependency test_codemirror "@ruzito/oas-ls-codemirror" "$semver"

# symlink the local override for .npmrc to publish @ruzito/* packages to localhost npm repo
for dir in backend frontend_* test_*
do
    (cd "$dir" && ln -fs ../.npmrc .npmrc)
done