#!/bin/bash
set -euxo pipefail

# $1 - project whose dependency's being edited
# $2 - dependency name
# $3 - dependency location

cd $1
jq '.dependencies."'"$2"'" = "'"$3"'"' package.json > new_package.json
mv new_package.json package.json
#sed -r 's#"@ruzito/oas-ls-codemirror": "(.*)"#"@ruzito/oas-ls-codemirror": "../frontend_codemirror"#g' package.json)