#!/bin/bash
set -euxo pipefail

mkdir -p verdaccio/conf
# mkdir -p verdaccio/storage
# mkdir -p verdaccio/plugins
# mkdir -p verdaccio/logs

touch verdaccio/conf/config.yaml

docker rm -f verdaccio

#     --volume `pwd`/verdaccio/storage:/verdaccio/storage \
#     --volume `pwd`/verdaccio/logs:/verdaccio/logs \
#     --volume `pwd`/verdaccio/plugins:/verdaccio/plugins \
#     --user `id -u`:`id -g` \
docker run -it --detach \
    --rm \
    --publish 4873:4873 \
    --volume `pwd`/verdaccio/conf:/verdaccio/conf \
    --name verdaccio \
    verdaccio/verdaccio \
    verdaccio --listen 0.0.0.0:4873 --config /verdaccio/conf/config.yaml

sleep 1.5

curl localhost:4873 > /dev/null
