#!/bin/bash
set -euxo pipefail

run/clean

run/.impl/start-local-npm

icmd=${1:-ci}

instFlags="--loglevel silent"
instFlags="--loglevel silly"

if [[ "$icmd" = "reinstall" ]]
then
    run/unlock
    icmd="install"
fi

# Independent layer
(cd backend && npm $icmd $instFlags && npm run build && npm publish)
run/.impl/remove-local-integrity-hash

# Frontend layer
(cd frontend_codemirror && npm $icmd $instFlags && npm run build && npm publish)
run/.impl/remove-local-integrity-hash

# End to end layer
(cd test_benchmarks && npm $icmd $instFlags && npm run build)
(cd test_integration && npm $icmd $instFlags && npm run build)
(cd test_codemirror && npm $icmd $instFlags && npm run build && touch src/main.ts)
run/.impl/remove-local-integrity-hash

# run/.impl/stop-local-npm

run/notify