#!/bin/bash
set -euxo pipefail

icmd=${1:-ci}

run/clean "$icmd"

run/.impl/start-local-npm


instFlags="--loglevel silent"
instFlags="--loglevel silly"

if [[ "$icmd" = "reinstall" ]]
then
    run/unlock
    icmd="install"
fi

# Independent layer
if [[ "$icmd" = "offline" ]]
then
    icmd=ci
    (cd backend && npm $icmd $instFlags && npm run build-skip-grammar && npm publish)
    run/.impl/remove-local-integrity-hash
else
    (cd backend && npm $icmd $instFlags && npm run build && npm publish)
    run/.impl/remove-local-integrity-hash
fi

# Frontend layer
(cd frontend_codemirror && npm $icmd $instFlags && npm run build && npm publish)
run/.impl/remove-local-integrity-hash

# End to end layer
(cd test_benchmarks && npm $icmd $instFlags && npm run build)
(cd test_integration && npm $icmd $instFlags && npm run build)
(cd test_codemirror && npm $icmd $instFlags && npm run build && touch src/main.ts)
run/.impl/remove-local-integrity-hash

# run/.impl/stop-local-npm

run/notify