#!/bin/bash
set -euo pipefail

# This script is used to publish the public packages to npm

function info() {
    echo "$1: $(cd $1 && npm pkg get name) $(cd $1 && npm pkg get version)"
}

function publish() {
    echo "Publishing $(info $1)"
    cd $1 && npm publish --@ruzito:registry=https://registry.npmjs.org/
}

run/fresh
run/test
echo
echo
echo "You are about to publish the following modules:"
echo "----------------------------------------------"
info backend
info frontend_codemirror
echo "----------------------------------------------"
read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Publishing..."
else
    echo "Aborted."
    exit 1
fi

publish backend
publish frontend_codemirror