#!/bin/bash
set -euxo pipefail

for component in "$@"
do
case "$component" in
  backend)
    (cd backend && npm run build)
    ;;

  backend-grammar)
    (cd backend && npm run build-grammar && npm run bundle)
    ;;

  backend-no-grammar)
    (cd backend && npm run build-asm && npm run build-asm && npm run bundle)
    ;;

  backend-asm)
    (cd backend && npm run build-asm && npm run bundle)
    ;;

  backend-tsc)
    (cd backend && npm run build-tsc && npm run bundle)
    ;;

  codemirror)
    (cd frontend_codemirror && npm run build)
    ;;

  codemirror-grammar)
    (cd frontend_codemirror && npm run build)
    ;;

  codemirror-tsc)
    (cd frontend_codemirror && npm run build-tsc)
    ;;

  web-codemirror)
    (cd test_codemirror && npm run build)
    ;;

  stop)
    run/notify
    exit 0
    ;;

  *)
    echo "Unknown component $component"
    exit 2
    ;;
esac
done

run/relink
run/notify