#!/bin/bash
set -euxo pipefail

# This script is used to rebuild only a part of the project,
# this is a fluid, dev-only script,
# feel free to modify it to your needs

for component in "$@"
do
case "$component" in
  backend)
    (cd backend && npm run build)
    ;;

  backend-grammar)
    (cd backend && npm run build-grammar && npm run bundle)
    ;;

  backend-skip-grammar)
    (cd backend && npm run build-skip-grammar)
    ;;

  backend-tsc)
    (cd backend && npm run build-tsc && npm run bundle)
    ;;

  codemirror)
    (cd frontend_codemirror && npm run build)
    ;;

  codemirror-grammar)
    (cd frontend_codemirror && npm run build)
    ;;

  codemirror-tsc)
    (cd frontend_codemirror && npm run build-tsc)
    ;;

  web-codemirror)
    (cd test_codemirror && npm run build)
    ;;

  stop)
    run/.impl/notify
    exit 0
    ;;

  *)
    echo "Unknown component $component"
    exit 2
    ;;
esac
done

run/.impl/relink
run/.impl/notify