#!/bin/bash
set -euxo pipefail

run/clean-local

run/.impl/start-local-npm

icmd=${1:-ci}

# Independent layer
(cd backend_asm_script && npm $icmd && npm run build && npm publish)
(cd backend_vanilla && npm $icmd && npm run build && npm publish)
run/.impl/remove-local-integrity-hash

# Frontend layer
(cd frontend_codemirror && npm $icmd && npm run build && npm publish)
run/.impl/remove-local-integrity-hash

# End to end layer
(cd test_benchmarks && npm $icmd && npm run build)
(cd test_integration && npm $icmd && npm run build)
(cd test_codemirror && npm $icmd && npm run build && touch src/main.ts)
run/.impl/remove-local-integrity-hash

# run/.impl/stop-local-npm
