#!/bin/bash
set -euo pipefail

run/rebuild

# Command in dir1
(
    cd test_codemirror || exit
    npm run dev > vite.log 2> vite.err.log
) &

# # Command in dir2
# (
#     cd monaco_test || exit
#     npm run dev > vite.log 2> vite.err.log
# ) &

sleep 2

echo 'Codemirror:'
grep 'http://' test_codemirror/vite.log

# echo 'Monaco:'
# grep 'http://' monaco_test/vite.log

wait