#!/bin/bash
set -euo pipefail

# This script is used to start example web projects on localhost

(
    cd test_codemirror || exit
    npm run dev > vite.log 2> vite.err.log
) &

# # Second project
# (
#     cd test_codemirror || exit
#     npm run dev > vite.log 2> vite.err.log
# ) &

sleep 2

echo 'Codemirror:'
grep 'http://' test_codemirror/vite.log

wait