name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        privileged: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Build & Test
        run: run/fresh && run/test